SKIP_UNRELEASED_VERSIONS = true

# Specify your gem's dependencies in cocoapods-bin-forest.gemspec


def cp_gem(name, repo_name, branch = 'master', path: false)
  return gem name if SKIP_UNRELEASED_VERSIONS
  opts = if path
           { :path => "../#{repo_name}" }
         else
           url = "https://github.com/CocoaPods/#{repo_name}.git"
           { :git => url, :branch => branch }
         end
  gem name, opts
end

source 'https://rubygems.org'


group :development do

  cp_gem 'cocoapods',                'cocoapods',path: 'CocoaPods'
  cp_gem 'xcodeproj',                'xcodeproj',path: 'Xcodeproj'
  cp_gem 'cocoapods-bin-forest',                'cocoapods-bin-forest',path: 'cocoapods-bin-forest'

  gem 'cocoapods-generate', '2.2.5'
  gem 'mocha'
  gem 'bacon'
  gem 'mocha-on-bacon'
  gem 'prettybacon'

end
